#include <EdgeImpulseModel.h> // Include the model header file generated by Edge Impulse

const int sensorPin = A0;

void setup() {
  Serial.begin(9600);
  // Initialize the Edge Impulse model
  if (!ei_impulse_start()) {
    Serial.println("Failed to initialize the model!");
    while (1);
  }
}

void loop() {
  int sensorValue = analogRead(sensorPin);
  float temperature = (sensorValue * (5.0 / 1023.0)) * 100.0;

  // Prepare features buffer and run the model
  ei_impulse_features[0] = temperature;
  ei_impulse_result_t result = ei_impulse_run();

  // Print the result
  Serial.print("Temperature: ");
  Serial.print(temperature);
  Serial.print(" - Predicted label: ");
  Serial.println(result.classification[0].label);

  delay(1000);
}