#include <DHT.h>
#include <EdgeImpulseModel.h> // Include the model header file generated by Edge Impulse

#define DHTPIN 2 // Pin where the DHT11 is connected
#define DHTTYPE DHT11
#define PIRPIN 3 // Pin where the PIR sensor is connected

DHT dht(DHTPIN, DHTTYPE);
const int tempSensorPin = A0;
const int lightSensorPin = A1;
const int soundSensorPin = A2;
const int airQualitySensorPin = A3;

void setup() {
  Serial.begin(9600);
  pinMode(PIRPIN, INPUT);
  dht.begin();
  // Initialize the Edge Impulse model
  if (!ei_impulse_start()) {
    Serial.println("Failed to initialize the model!");
    while (1);
  }
}

void loop() {
  // Read all sensor values
  float temperature = analogRead(tempSensorPin) * 0.48828125; // Direct conversion for efficiency
  float humidity = dht.readHumidity();
  float temperatureDHT = dht.readTemperature();
  int lightLevel = analogRead(lightSensorPin);
  int soundLevel = analogRead(soundSensorPin);
  int airQualityLevel = analogRead(airQualitySensorPin);
  int pirState = digitalRead(PIRPIN);

  // Check for DHT11 errors
  if (isnan(humidity) || isnan(temperatureDHT)) {
    Serial.println("Failed to read from DHT;
  }

  // Prepare features buffer and run the model
  ei_impulse_features[0] = temperature;
  ei_impulse_features[1] = humidity;
  ei_impulse_features[2] = lightLevel;
  ei_impulse_features[3] = soundLevel;
  ei_impulse_features[4] = airQualityLevel;
  ei_impulse_features[5] = pirState;
  ei_impulse_result_t result = ei_impulse_run();

  // Print the results efficiently
  Serial.print("LM35 Temp: "); Serial.print(temperature); Serial.print("°C, ");
  Serial.print("DHT11 Temp: "); Serial.print(temperatureDHT); Serial.print("°C, ");
  Serial.print("Humidity: "); Serial.print(humidity); Serial.print("%, ");
  Serial.print("Light: "); Serial.print(lightLevel); Serial.print(", ");
  Serial.print("Sound: "); Serial.print(soundLevel); Serial.print(", ");
  Serial.print("Air Quality: "); Serial.print(airQualityLevel); Serial.print(", ");
  Serial.print("Motion: "); Serial.print(pirState ? "Detected" : "Not Detected");
  Serial.print(" - Prediction: "); Serial.println(result.classification[0].label);

  // Minimal delay for processing time
  delay(1000);
}