#include <DHT.h>
#include <EdgeImpulseModel.h> // Include the model header file generated by Edge Impulse

#define DHTPIN 2 // Pin where the DHT11 is connected
#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);
const int tempSensorPin = A0;

void setup() {
  Serial.begin(9600);
  dht.begin();
  // Initialize the Edge Impulse model
  if (!ei_impulse_start()) {
    Serial.println("Failed to initialize the model!");
    while (1);
  }
}

void loop() {
  // Read temperature from LM35
  int tempSensorValue = analogRead(tempSensorPin);
  float temperature = (tempSensorValue * (5.0 / 1023.0)) * 100.0;

  // Read humidity from DHT11
  float humidity = dht.readHumidity();
  float temperatureDHT = dht.readTemperature();

  if (isnan(humidity) || isnan(temperatureDHT)) {
    Serial.println("Failed to read from DHT sensor!");
    return;
  }

  // Prepare features buffer and run the model
  ei_impulse_features[0] = temperature;
  ei_impulse_features[1] = humidity;
  ei_impulse_result_t result = ei_impulse_run();

  // Print the result
  Serial.print("LM35 Temperature: ");
  Serial.print(temperature);
  Serial.print(" °C, DHT11 Temperature: ");
  Serial.print(temperatureDHT);
  Serial.print(" °C, Humidity: ");
  Serial.print(humidity);
  Serial.print(" % - Predicted label: ");
  Serial.println(result.classification[0].label);

  delay(2000); // Delay for 2 seconds
}
